name: DevOps Quote App CI

# Startet automatisch bei jedem Git Push auf den main-Branch
on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Code aus dem GitHub-Repository auschecken
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Docker Build-Umgebung einrichten
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Testen, ob sich das Docker Image bauen lässt
      - name: Build Docker Image
        run: |
          docker build -t devops-quote-app:${{ github.sha }} .
          echo "Pipeline erfolgreich! Der Docker Build hat funktioniert."