name: DevOps Quote App CI

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Code auschecken
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Python auf dem Runner einrichten
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. SYNTAX-CHECK (Prüft auf Tippfehler wie 'retun')
      - name: Check Python Syntax
        run: |
          python -m py_compile app.py

      # 4. Docker Build (wird nur ausgeführt, wenn Schritt 3 erfolgreich war!)
      - name: Build Docker Image
        run: |
          docker build -t devops-quote-app:${{ github.sha }} .